### ISSUE TITLE
直接上传之后无法使用，搜索功能有问题，只能显示主页，帮助页显示也有问题

### ISSUE THREAD

**Issue by qwqdanchun** [ChenYFan/music#1]

**Comment by ChenYFan** [comment]
呃呃呃呃，这个脚本是拷贝来自刘明野的工具，本人还没有完全修改完毕，搜索功能接口API有些被关闭了，我还没有找到足够的接口，缺陷仍然非常多。但我个人使用时QQ音乐是可以搜索的，如果只能显示主页，请以http访问。电脑版https还可以勾选“允许加载不安全的脚本”来正常加载。
PS：本人没有完全熟悉脚本，最近也没有空，修复一事还是要您们多多帮助。

**Comment by ChenYFan** [comment]
对了，你过了学历验证吗？如果你过了，那昨天访问不上的原因是000webhost短暂性宕机。如果你是自己部署的，你可以尝试部署在heroku上，再以http访问。
PS：酷狗音乐解析API确认已失效，如果没有接口，我将删除酷狗音乐解析。

**Comment by qwqdanchun** [comment]
额，昨天下载回来直接上传了，之后就有问题，感觉是自己哪里出的问题，因为几个实例网站都可以正常用。。。
你可以看下，http://music.dcyy.fun,这个是源码一点没动上传之后的效果，环境php71和54都试过

**Comment by qwqdanchun** [comment]
代码还在看，但是我还没有找到问题在哪
ps：那个学历验证好骚啊，你一定扛着品如的衣柜吧，哈哈哈

**Comment by qwqdanchun** [comment]
问题应该出在搜索结果没有返回
http://music1.dcyy.fun/ajax/search/text/546L5Yqb5a6P/page/1/type/baidu/token/441929fab91da24a92007d85afd4021b
http://tools.cyfan.ga/unpublicmusic/ajax/search/text/546L5Yqb5a6P/page/1/type/qq/token/98c488f103ebab8463c55755f633eebf
同样搜索王力宏，但是这个我那个就返回404

**Comment by ChenYFan** [comment]
你是放在域名根目录吗？你可以试一试二级根目录（我觉得不太可能）。
要么确保程序有写入缓存的权限。
PS：我要下线了才看到的，今天估计不会再回复了。
又PS：你居然过了学历验证？厉害厉害

**Comment by qwqdanchun** [comment]
二级目录和权限都试了，没问题
我抽空再接着看代码吧

**Comment by ChenYFan** [comment]
说明一下：我的学历验证是伪验证，麻烦您不要把网址发出来。
是不是你的php服务商有问题？我heroku和000webhost全部实验通过了呀。

**Comment by ChenYFan** [comment]
您是不是误删了代码？我发现你把界面都换了。你试试源代码直接不修改使用。

**Comment by qwqdanchun** [comment]
这个是测试用的域名，测试之后就不用了的，不用担心
我放在自己的服务器里的，可能php配置出问题了？
我再试试吧

**Comment by ChenYFan** [comment]
你能告诉我你的php运行商吗？
### ps：我的学历验证是伪验证，麻烦您不要把我的网址发出来。不是你的域名，我指的是我的工具箱。

**Comment by ChenYFan** [comment]
另外，我的工具箱使用一切正常 （除了一些接口被禁），可能就是你的php服务商问题了。
ps：一些国内的运营商禁用了一些php函数，

**Comment by qwqdanchun** [comment]
哦哦，域名删了，另外我是自己的服务器，不是php服务那种

**Comment by ChenYFan** [comment]
..........自己的服务器？那php你可能需要勾选“允许访问外网”，并且允许所有函数。
ps：没事没事，删了就好。

**Comment by ChenYFan** [comment]
帮助页显示本人测试并无问题。你看看是不是自己服务器有问题。

**Comment by qwqdanchun** [comment]
https://music-qwqdanchun.herokuapp.com/
heroku直接对接我fork过来的项目，还是都不好使
000官网挂了，晚点试

**Comment by ChenYFan** [comment]
我明白了，在你试一试Apache伪静态，添加一个空白的.htaccess试试

**Comment by ChenYFan** [comment]
实在不行的话那我明天重新发一遍修改过的代码吧，有可能我忘记添加了什么。
明天再试试吧。

**Comment by qwqdanchun** [comment]
好的，麻烦你了

**Comment by ChenYFan** [comment]
嗯嗯，没事，有可能就是我的问题了。

**Comment by ChenYFan** [comment]
呃呃呃呃，回来回来

**Comment by ChenYFan** [comment]
我找到原因了。
你在原文件根下添加一个.htaccess，里面填写：
<IfModule mod_rewrite.c>
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php [L,E=PATH_INFO:$1]
</IfModule>

**Comment by ChenYFan** [comment]
不对不对，不用复制了，我自己添加吧。

**Comment by ChenYFan** [comment]
好了，我做好了，麻烦你重新Fork部署一下吧。
真是麻烦你了，为了这个bug追了我一整天，原来是我忘记添加.htaccess了。

**Comment by ChenYFan** [comment]
你试一试，如果能用，麻烦说一声，我就关闭这个issues

**Comment by qwqdanchun** [comment]
好了，这次可以了
谢谢啦

**Comment by ChenYFan** [comment]
没事没事，辛苦了。
你也可以订阅我的博客，我打算明天谈谈这个问题。

**Comment by qwqdanchun** [comment]
好的
